### ISSUE TITLE
regarding spending of notes by creator after sharing 

### ISSUE THREAD

**Issue by HiteshMittal07** [StrawberryChocolateFudge/Bunny-Notes#3]
[BunnyNotes.zip](https://github.com/StrawberryChocolateFudge/Bunny-Notes/files/14966986/BunnyNotes.zip)
This file contain the updated code for stop using of note after sharing, when the note is shared the receiver should verify the note and same section of the page will contain a scanner for verifying plus changing ownership , which will trigger the function changeOwner, a complete new note will be created and other will be deleted, the funds will now be associated with new commitment , for gas problems layer 2 solutions can be used which will solve the problem of creator spending the note

**Comment by HiteshMittal07** [comment]
I have provided the solution with the issue itself so make sure to check out and reply on further problems

**Comment by StrawberryChocolateFudge** [comment]
Hi. You can open a pull request and I will review the diff. I removed the stale branches from the repo, you can use the new "main" branch as your target.
